name: Publish WinForms Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish WinForms Project
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: winforms-publish
        path: ./publish
